### ISSUE TITLE
Can't set a sound

### ISSUE THREAD

**Issue by OboTheHobo** [dewiniaid/hexchat-scripts#4]
I am doing the command "/alerts sound ratsignal [ratsignal.wav]" and when I run it I get the following error:
Traceback (most recent call last):
   File "<string>", line 2255, in command_hook
   File "<string>", line 1323, in call
   File "<string>", line 1456, in wrapper
 IndexError: list index out of range
 Traceback (most recent call last):
   File "<string>", line 2255, in command_hook
   File "<string>", line 1323, in call
   File "<string>", line 1456, in wrapper
 IndexError: list index out of range
 Traceback (most recent call last):
   File "<string>", line 2255, in command_hook
   File "<string>", line 1323, in call
   File "<string>", line 1456, in wrapper
 IndexError: list index out of range
 Traceback (most recent call last):
   File "<string>", line 2255, in command_hook
   File "<string>", line 1323, in call
   File "<string>", line 1456, in wrapper
 IndexError: list index out of range

**Comment by OboTheHobo** [comment]
as well I have tried many alternatives and yes, it does work using /splay

**Comment by RyanWolfe556** [comment]
I am having the same issue. 

However, I have discovered a way around this, use
`/alerts set <alert> sound [<soundfile>|OFF]`
and that works just fine.

A side note of this, if you install HexChat outside of main C:\ then you cannot find the audio files.

**Comment by tyrope** [comment]
Is this a HexChat limitation, or a plugin limitation? Seems silly that %appdata% isn't accessible outside a C:\ install, perhaps we need to run it with admin privileges?

**Comment by Poikilos** [comment]
@tyrope  The purpose of %APPDATA% is storing user-specific settings and data without admin priveleges. The problem may be spaces in the path, or assuming C: when translating from unix-like paths, if that is a problem somewhere in the code. @RyanWolfe556 By "outside of main c:\" do you mean on another drive letter, or somewhere deeper? What is the install path that does not work?

**Comment by Poikilos** [comment]
@dewiniaid Are you here? The issue seems to be a missing length checking for the params list. The same occurs in 2.14.3 on Fedora 31:
```
Traceback (most recent call last):
   File "/home/owner/.config/hexchat/addons/alerts.py", line 2255, in command_hook
     event.call()
   File "/home/owner/.config/hexchat/addons/alerts.py", line 1323, in call
     self.fn(self)
   File "/home/owner/.config/hexchat/addons/alerts.py", line 1456, in wrapper
     args.append(event.word_eol[max_args - 1])
```

### Expected behavior:
- If the param after `/alert` is a setting, say: `print("Your syntax is incorrect. To set variables you must do /alerts set <alert> {setting_name} <value>.".format(setting_name=params[0]))` or where params[0] is the setting that should instead be a command.
